# Generated by Django 4.1.7 on 2023-03-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='photo',
        ),
    ]
